services:
  - type: web
    name: directus
    env: image
    image:
      url: directus/directus:11.6.1
    plan: free
    autoDeploy: true
    region: oregon
    envVars:
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: PUBLIC_URL
        sync: false
      - key: SECRET
        sync: false
